environment_variables: {}
external_package_dirs: []
model_metadata: {}
model_name: arible-cartoonify
python_version: py311
requirements:
  - diffusers==0.25.1
  - huggingface_hub==0.20.2
  - transformers==4.37.1
  - torch==2.0.0
  - torchvision==0.15.1
  - numpy
  - pillow
  - opencv-python
  - accelerate
  - safetensors
  - einops
  - onnxruntime-gpu
  - insightface
  - controlnet_aux
  - peft
resources:
  accelerator: A10G
  cpu: "4"
  memory: 8Gi
  use_gpu: true
secrets: {}
system_packages:
  - libgl1
external_data:
  - url: "https://civitai.com/api/download/models/294470?type=Model&format=SafeTensor&size=pruned&fp=fp16"
    local_data_path: realisticStockPhoto_v20.safetensors
  - url: https://huggingface.co/InstantX/InstantID/resolve/main/ControlNetModel/config.json?download=true
    local_data_path: ControlNetModel/config.json
  - url: https://huggingface.co/InstantX/InstantID/resolve/main/ControlNetModel/diffusion_pytorch_model.safetensors?download=true
    local_data_path: ControlNetModel/diffusion_pytorch_model.safetensors
  - url: https://huggingface.co/InstantX/InstantID/resolve/main/ip-adapter.bin?download=true
    local_data_path: ip-adapter.bin
  - url: "https://pub-7bbc6377635e4e588a0a4c5fdfb0df93.r2.dev/1k3d68.onnx"
    local_data_path: models/insightface/models/antelopev2/1k3d68.onnx
  - url: "https://pub-7bbc6377635e4e588a0a4c5fdfb0df93.r2.dev/2d106det.onnx"
    local_data_path: models/insightface/models/antelopev2/2d106det.onnx
  - url: "https://pub-7bbc6377635e4e588a0a4c5fdfb0df93.r2.dev/genderage.onnx"
    local_data_path: models/insightface/models/antelopev2/genderage.onnx
  - url: "https://pub-7bbc6377635e4e588a0a4c5fdfb0df93.r2.dev/glintr100.onnx"
    local_data_path: models/insightface/models/antelopev2/glintr100.onnx
  - url: "https://pub-7bbc6377635e4e588a0a4c5fdfb0df93.r2.dev/scrfd_10g_bnkps.onnx"
    local_data_path: models/insightface/models/antelopev2/scrfd_10g_bnkps.onnx
