environment_variables: {}
external_package_dirs: []
model_metadata: {}
model_name: arible-qr-code
python_version: py311
requirements: []
resources:
  accelerator: null
  cpu: '1'
  memory: 2Gi
  use_gpu: false
secrets: {}
system_packages: []
