environment_variables: {}
external_package_dirs: []
model_metadata: {}
model_name: arible-qr-code
python_version: py311
requirements:
  - diffusers
  - transformers
  - torch
  - pillow
  - accelerate
  - safetensors
  - xformers
  - qrcode
  - pyzbar
resources:
  accelerator: A10G
  cpu: "4"
  memory: 4Gi
  use_gpu: true
secrets: {}
system_packages:
  - libzbar0
