environment_variables: {}
external_package_dirs: []
model_metadata: {}
model_name: arible-headshots
python_version: py311
requirements: []
resources:
  accelerator: null
  cpu: "1"
  memory: 2Gi
  use_gpu: true
secrets: {}
system_packages: []
